parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  project: './tsconfig.json'

env:
  browser: true
  es6: true

overrides:
  - files:
      - '*.spec.ts'
    env:
      es6: true
      jasmine: true
      jest: true
      node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:cypress/recommended'
  - 'prettier'

rules:
  no-console:
    - warn
    - allow:
        - info
        - warn
        - error
  no-alert: error
  no-restricted-imports:
    - error
    - patterns:
        - 'rxjs/Rx'
  'default-param-last':
    - off
  no-shadow:
    - off
  # Require that semicolons are not used unless required.
  semi:
    - off
  '@typescript-eslint/semi':
    - 'error'
    - never
  '@typescript-eslint/no-extra-semi':
    - off
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/default-param-last': error
  '@typescript-eslint/no-confusing-non-null-assertion': error
  '@typescript-eslint/no-dynamic-delete': error
  '@typescript-eslint/no-for-in-array': error
  '@typescript-eslint/no-implied-eval': error
  '@typescript-eslint/no-throw-literal': error
  # this conflicts with angular SimpleChanges
  # '@typescript-eslint/no-unnecessary-condition': warn
  '@typescript-eslint/no-unnecessary-type-arguments': error
  '@typescript-eslint/no-unnecessary-type-assertion': error
  '@typescript-eslint/prefer-for-of': error
  '@typescript-eslint/prefer-includes': error
  '@typescript-eslint/prefer-nullish-coalescing': warn
  '@typescript-eslint/prefer-optional-chain': warn
  '@typescript-eslint/prefer-reduce-type-parameter': error
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-string-starts-ends-with': error
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
  '@typescript-eslint/no-non-null-assertion':
    - off
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/explicit-member-accessibility':
    - error
    - accessibility: no-public
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - arrowFunctions
  '@typescript-eslint/explicit-module-boundary-types':
    - off
